type Athlete = {
  athlete_id?: number; // Optional because it's auto-generated by the database
  full_name: string;
  date_of_birth: string; // We use string to make it easier to handle input fields and JSON serialization
  gender: string;
  returner_status: string;
  parent_id?: number; // This can be optional if you assign it after creating the parent
};

export default Athlete;