import Athlete from './Athlete';

type Parent = {
    parent_id?: number; // optional as it's generated by the database
    email: string;
    phone_number: string;

    athletes: Athlete[];
  };
  
  export default Parent;